name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: pipx install uv
    - uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
        cache: pip
    - name: Install dependencies
      run: |
        uv sync
    - name: Run tests
      id: run-tests
      run: >
        uv run pytest \
          --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml:coverage.xml \
          --cov=src tests \
          --verbose
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install uv
          uv sync
          uv run mypy .
